project:
  type: book

book:
  title: "Acoustic Telemetry Standard Operating Procedures"
  version: "0.0.1"
  date: "12/18/2024"
  chapters:
    - index.qmd
    - fathom_connect.qmd
    - releases.qmd
    - transport_and_storage.qmd
    - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo



