# Acoustic Release Deployment and Recovery

## Innovasea VR2AR and ASCENT release and recovery

::: {.callout-note collapse="true"}
Adapted from protocols developed by Bonnie Ahr, Kennedy Space Center.
:::

  - Place VR100 on flat surface when possible
  - Only connect the transponding hydrophone when receiver is powered OFF.
  - Select **TRANSPOND** from VR100 main menu
  - If "**CANNOT COMMUNICATE WITH TRANSPONDER**[^1] appears, disconnect and reconnect the hydrophone then select **TRANSPOND** again
  - Wait for the vessel to stop moving
  - Place hydrophone in water and select **TRANSPOND** from VR100 main menu
  - Select the **ADD DEVICE** option manually or by pressing "**2**"
  - ADD the serial number of the unit you are hoping to release and press **OK**
  - Select **ACOUSTIC RELEASE** manually or by pressing "**3**"
  - Select **ACTIVATE** manually or by pressing "**3**" again
  - Listen for a response from the receiver through the VR100 speaker; "**Sx**", where "**x**" is a number, may also flash on the screen. If the response is successfully received and decoded, you will see the message saying "**Opening**" in the deck box screen and the distance of the hydrophone from the receiver. If you heard a response from the speaker in the form of rhythmic "clicks" but did not see an "Opening" message, the unit has still been released
  - After a few seconds, Select **STATUS** to update the release status and depth. If the release is successful, the screen will show the message "**Open**" and you should notice the depth changed. If the receiver is stuck at the same depth after a few **STATUS** attempts, you can consider the unit "stuck"

[^1]: Wording approximate. To be updated when someone gets eyes-on.


### Troubleshooting

#### Poor Communication
  - Set **TRANSMIT POWER** to a lower setting to reduce echo noise. The default is 7 (high). Moving 30-50m from the location of the receiver may also help.
  - You can also switch the detection parameter between Near, Normal, and Far. Most units will communicate better in the Normal setting, but if there is trouble establishing a connection, it is worth trying the other settings.
  - Move the hydrophone away from the vessel’s depth transponder or turn the depth transponder off if you hear constant rapid clicking; depth transponders emit noise at 69 kHz that may interfere with communication. 
  - If current, tides, or winds are strong-enough to make the vessel drift as indicated by the hydrophone cable running at an angle from the vessel, move the vessel so that the angle of the hydrophone’s cable points roughly in the direction of the receiver.
  - Select **STATUS**/**GET RANGE** to establish a communications link. This is particularly good to check on some parameters such as depth, tilt and horizontal range ("hRange") information. This range is often accurate to the distance where the equipment will surface in relation to the vessel. Tilt will be able to indicate if the mooring is still straight up, which means recovery will be successful if the equipment release mechanism does not fail.
  - Select **AUTOSCAN** (**TRANSPOND** > Option 1) to wake up all receivers within listening distance. Useful in case of lost or mis-recorded receiver serial numbers.
    - The length of time the VR100 listens for a response during **AUTOSCAN** increases each time this option is selected. It may be necessary to reset the transponding session after multiple failed connections to reduce the listening time and increase the frequency of connection attempts. Note that this also resets any custom configurations including the transmission power level. To reset the session, Select **TRANSPONDING** from the main menu (3rd option), then **RESET SESSION** (3rd option).
    
#### Receiver not surfacing

Possible causes:

  - Obstructions
    - fishing line or gear, tree branches, discarded dishwashers
  - Biofouling causing loss in buoyancy of buoy
  - Sedimentation and burial
  - Low battery
    - In some instances of very low receiver battery, replying to a **STATUS** or **GET RANGE** command will deplete the battery enough to prevent a complete release.


## Innovasea VR2AR and ASCENT release deployment

### Pre-deployment

#### VR2AR

  - Offload receiver data using VUE or [Fathom Connect](fathom_connect.qmd)
  - Rebattery VR2AR. Batteries last approximately 14 months.
  - Reset battery use indicator when prompted in VUE or Fathom Connect.
  - Note if the internal motor release battery needs to be changed. The release battery is different from the receiver battery. Refer to the [Innovasea guide linked here](https://support.fishtracking.innovasea.com/s/article/When-should-I-replace-my-VR2AR-ASCENT-acoustic-release-battery).
  - Rearm lug with retaining pin and O-ring. Both are critical. Make sure to grease upper half of lug copper sleeve and internal threaded rod.
  - If using VUE, make sure that temperature, tilt, depth and noise sensors are recording by clicking **TRANSMITTER OPTIONS**, found under the gear icon
  - For all four sensors, check **LOG STATS** buttons with a period of 3600 sec. Do not select **LOG SAMPLES**.
  - If receivers will be deployed within 1 km of each other, set the internal transmitter with Profile=Sync Tag, Power=Very High.
    - VUE: gear icon -> **TRANSMITTER OPTIONS**
    - Fathom Connect: *Self-Transmitter* tab; [further information here.](#internal-transmitter)

#### VR100

  - Plug charging cable into AC or DC source and drybox port
  - Keep drybox on flat surface and out of hot sun to avoid faults
  - Charging is complete in 14 hours
  - Receiver is functional when charging but may decrease performance
  - Battery life 12 hours but less with backlight on
  - Receiver can remain charging for extended periods (days)
  - Charge every 3-4 months when in storage and never completely discharge battery

### Deployment

  - Drop mooring/receiver as close as possible to+/- 2 m from planned location. It is likely that the mooring will move 2-10m from location of deployment during descent if released freely from surface.
  - If time allows, check tilt of sensor after deployment using the **STATUS**/**GET RANGE** process outlined above
